### ISSUE TITLE
Failed to get recent VSCode entries; Expected type utf8 for Argument "uri" but got type "Object"

### ISSUE THREAD

**Issue by Bernd-L** [Jomik/vscode-search-provider#27] opened 2020-02-07 06:37 UTC
## General

I've just downloaded the extension, and it doesn't work; I get an error message.

![image](https://user-images.githubusercontent.com/18219148/74006114-fc8a9600-497a-11ea-9ba7-365ccb470679.png)

The appears to be displayed here:
https://github.com/Jomik/vscode-search-provider/blob/08417311917a84fa6640d06edb1bc5fc05745e3b/extension.ts#L390

I do not know what the error message means.

Issue #9 already talked about trouble with the OSS version of VS Code.

## Me trying to fix this

I treid to fix this myself by creating a link:

```shell
ln -s ~/.vscode-oss ~/.vscode
```

But this didn't change anything. I still get the same error.

I have some experience with TypeScript and will likley look into this further when I have more time.

## Versions

It might be helpful to know which version of VS Code and Distro I'm running (and so on):

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-20T11:11:01.597Z
Electron: 6.1.7
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.4.15-2-MANJARO
```

**Comment by lunaryorn** [comment] 2020-02-07 07:23
We do support VSCode OSS; in fact I'm using it myself. The error message occurs at a place where the extension already found your VSCode installation.  It somehow fails to read its recent projects, but I've never seen that error before.

There's an l function in the code which logs to journalctl; try adding it all over the affected code to see where it actually fails.  Perhaps you can also produce a stacktrace (don't know if gjs supports this), that's help tremendously to pinpoint the cause.

**Comment by lunaryorn** [comment] 2020-02-07 07:25
That said please undo your fix; it has no effect on any case, and I do not know whether both editions are fully compatible 🙂

**Comment by Bernd-L** [comment] 2020-02-07 07:25
> occurs at a place where the extension already found your VSCode installation

That's interesting.

> That said please undo your fix; it has no effect on any case, and I do not know whether both editions are fully compatible slightly_smiling_face
U already did

**Comment by Jomik** [comment] 2020-02-07 14:59
Could sounds like an error here:
https://github.com/Jomik/vscode-search-provider/blob/08417311917a84fa6640d06edb1bc5fc05745e3b/extension.ts#L307
https://github.com/Jomik/vscode-search-provider/blob/08417311917a84fa6640d06edb1bc5fc05745e3b/extension.ts#L346

So maybe we should look at your `storage.json` ? :)

**Comment by lunaryorn** [comment] 2020-02-08 11:04
@Bernd-L I pushed a change which tries to log stacktraces for all thrown errors. Please clone the latest `master`, then run the following commands to install the extension:

```console
$ yarn
$ yarn compile
$ yarn package
$ gnome-extensions install vscode-search-provider@jomik.org.shell-extension.zip
```

Then log out and in again, wait till you see the error notification, and then check `journalctl -u` for messages from the `vscode-search-provider` extension.  It should hopefully include a stacktrace; if you see one, please paste it here.

**Comment by Bernd-L** [comment] 2020-02-09 11:21
Thanks for your reply @lunaryorn .

I uninstalled the official extension.
I cloned at master, and ran all 4 commands you listed previously.
Then I relogged.


<pre><font color="#00AA00"><b>➜  </b></font><font color="#00AAAA"><b>~</b></font> journalctl -u vscode-search-provider
-- Logs begin at Sat 2019-10-19 09:58:03 CEST, end at Sun 2020-02-09 11:58:25 CET. --
-- No entries --
<font color="#00AA00"><b>➜  </b></font><font color="#00AAAA"><b>~</b></font></pre>

It's not working.


But after running `journalctl --pager-end` I  found this:
```
Feb 09 12:05:51 bernd-pc gnome-shell[22997]: VSCode Search Provider: Found code at desktop app code-oss.desktop
```

The previous error messages I was receiving (via a popup-notification) are now gone.

The extension still doesn't work.

**Comment by Jomik** [comment] 2020-02-09 12:05
Can you paste a gist of your storage.json? It should be in your `~/.config/Code - OSS/` folder, or something similar.

**Comment by lunaryorn** [comment] 2020-02-15 13:34
@Bernd-L Ping :)

**Comment by lunaryorn** [comment] 2020-03-21 07:36
I'm closing this; feel free to open again if the issue still exists.

**Closed by lunaryorn** 2020-03-21 07:36 UTC
Labels: bug
